### ISSUE TITLE
Example fails on dt.compute

### ISSUE THREAD

**Issue by nlgranger** [hbristow/distance-transform#1]
Hello,

Thank you for working on this implementation of the distance transform. I have installed the project according to the README, but the example does not work as expected:

```
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dt
>>> import numpy as np
>>> 
>>> x = np.random.standard_normal((100,100))
>>> y,i = dt.compute(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dt.pyx", line 81, in dt.compute (dt.c:2639)
TypeError: 'map' object does not support item assignment
```

Any idea on what is going on?

**Comment by emckenzi123** [comment]
This is because it was written in Python 2.  To get it working in Python3, you need to replace line 80 with:
[line 80]  `slices = list(map(range, shape))`
